kind: Namespace
apiVersion: v1
metadata:
  name: kyma-system
---
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: kyma-system
value: 99
globalDefault: false
description: "This priority class should be used for Kyma pods only."
