run:
  allow-parallel-runners: true
output:
  format: "colored-tab:stderr,github-actions:stdout"
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: false
linters:
  disable-all: true
  enable:
    - errcheck
    - goimports
    - govet