name: kyma-project.io/module/btp-operator
team: kyma/gopher
images:
- europe-docker.pkg.dev/kyma-project/prod/btp-manager:1.3.17
- europe-docker.pkg.dev/kyma-project/prod/external/ghcr.io/sap/sap-btp-service-operator/controller:v0.11.6
- europe-docker.pkg.dev/kyma-project/prod/ca-bundle-probe:1.3.17
