---
# Source: sap-btp-operator/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator
  namespace: kube-public
type: Opaque
data:
  clientid: ""
  sm_url: ""
  tokenurl: ""
  tokenurlsuffix: "L29hdXRoL3Rva2Vu"
