---
# Source: sap-btp-operator/templates/secret.yml
apiVersion: v1
kind: Secret
metadata:
  name: sap-btp-service-operator
  namespace: kyma-system
  labels:
    "services.cloud.sap.com/managed-by-sap-btp-operator": "true"
type: Opaque
data:
  clientid: ""
  sm_url: ""
  tokenurl: ""
  tokenurlsuffix: "L29hdXRoL3Rva2Vu"
