---
# Source: sap-btp-operator/templates/webhook.yml
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: sap-btp-operator-mutating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: kyma-system
        path: /mutate-services-cloud-sap-com-v1-servicebinding
    failurePolicy: Fail
    name: mservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: kyma-system
        path: /mutate-services-cloud-sap-com-v1-serviceinstance
    failurePolicy: Fail
    name: mserviceinstance.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - serviceinstances
    sideEffects: None
---
# Source: sap-btp-operator/templates/webhook.yml
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: sap-btp-operator-validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: kyma-system
        path: /validate-services-cloud-sap-com-v1-servicebinding
    failurePolicy: Fail
    name: vservicebinding.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
        resources:
          - servicebindings
    sideEffects: None
  - admissionReviewVersions:
      - v1beta1
      - v1
    clientConfig:
      service:
        name: sap-btp-operator-webhook-service
        namespace: kyma-system
        path: /validate-services-cloud-sap-com-v1-serviceinstance
    failurePolicy: Fail
    name: vserviceinstance.kb.io
    rules:
      - apiGroups:
          - services.cloud.sap.com
        apiVersions:
          - v1
        operations:
          - DELETE
        resources:
          - serviceinstances
    sideEffects: None
