---
# Source: sap-btp-operator/templates/configmap.yml
apiVersion: v1
data:
  CLUSTER_ID: f8c4e0ec-f24e-4628-a359-20460d6cb549
  MANAGEMENT_NAMESPACE: kube-public
  RELEASE_NAMESPACE: kube-public
  ALLOW_CLUSTER_ACCESS: "true"
kind: ConfigMap
metadata:
  name: sap-btp-operator-config
  namespace: kube-public
