apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sap-btp-manager
  namespace: kyma-system
  labels:
    app.kubernetes.io/managed-by: kcp-kyma-environment-broker
data:
  clientid: ${SM_CLIENT_ID}
  clientsecret: ${SM_CLIENT_SECRET}
  sm_url: ${SM_URL}
  tokenurl: ${SM_TOKEN_URL}
  cluster_id: dGVzdF9jbHVzdGVyX2lk
