apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-001
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-002
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-003
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-004
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-005
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-006
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-007
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-008
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-009
  namespace: kyma-system
data:
  testData: test
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ${SECRET_NAME}-000
  namespace: kyma-system
data:
  testData: test
