apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-001
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-002
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-003
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-004
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-005
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-006
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-007
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-008
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-009
  namespace: kyma-system
data:
  testData: "abcd"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ${CM_NAME}-000
  namespace: kyma-system
data:
  testData: "abcd"