apiVersion: v1
kind: Service
metadata:
  name: metrics-service
  namespace: kyma-system
  labels:
    app.kubernetes.io/name:  btp-manager.kyma-project.io
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
spec:
  selector:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: metrics-service
  namespace: kyma-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/component: btp-manager.kyma-project.io
  portLevelMtls:
    "8080":
      mode: PERMISSIVE