# Prometheus Service (Metrics)
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: metrics-service
  namespace: kyma-system
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/component: btp-manager.kyma-project.io
