# Prometheus Service (Metrics)
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: controller-manager-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
  selector:
    app.kubernetes.io/component: btp-manager.kyma-project.io
