# permissions for end users to edit btpoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: btpoperator-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpoperators/status
  verbs:
  - get
