// Code generated by mockery v2.43.1. DO NOT EDIT.

package servicemanager

import (
	context "context"
	http "net/http"

	mock "github.com/stretchr/testify/mock"

	types "github.com/kyma-project/btp-manager/internal/service-manager/types"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// CreateServiceBinding provides a mock function with given fields: sb
func (_m *Client) CreateServiceBinding(sb *types.ServiceBinding) (*types.ServiceBinding, error) {
	ret := _m.Called(sb)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceBinding")
	}

	var r0 *types.ServiceBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.ServiceBinding) (*types.ServiceBinding, error)); ok {
		return rf(sb)
	}
	if rf, ok := ret.Get(0).(func(*types.ServiceBinding) *types.ServiceBinding); ok {
		r0 = rf(sb)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.ServiceBinding) error); ok {
		r1 = rf(sb)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateServiceInstance provides a mock function with given fields: si
func (_m *Client) CreateServiceInstance(si *types.ServiceInstance) (*types.ServiceInstance, error) {
	ret := _m.Called(si)

	if len(ret) == 0 {
		panic("no return value specified for CreateServiceInstance")
	}

	var r0 *types.ServiceInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.ServiceInstance) (*types.ServiceInstance, error)); ok {
		return rf(si)
	}
	if rf, ok := ret.Get(0).(func(*types.ServiceInstance) *types.ServiceInstance); ok {
		r0 = rf(si)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.ServiceInstance) error); ok {
		r1 = rf(si)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Defaults provides a mock function with given fields: ctx
func (_m *Client) Defaults(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Defaults")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteServiceBinding provides a mock function with given fields: serviceBindingId
func (_m *Client) DeleteServiceBinding(serviceBindingId string) error {
	ret := _m.Called(serviceBindingId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(serviceBindingId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteServiceInstance provides a mock function with given fields: serviceInstanceID
func (_m *Client) DeleteServiceInstance(serviceInstanceID string) error {
	ret := _m.Called(serviceInstanceID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteServiceInstance")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(serviceInstanceID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ServiceBinding provides a mock function with given fields: serviceBindingId
func (_m *Client) ServiceBinding(serviceBindingId string) (*types.ServiceBinding, error) {
	ret := _m.Called(serviceBindingId)

	if len(ret) == 0 {
		panic("no return value specified for ServiceBinding")
	}

	var r0 *types.ServiceBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.ServiceBinding, error)); ok {
		return rf(serviceBindingId)
	}
	if rf, ok := ret.Get(0).(func(string) *types.ServiceBinding); ok {
		r0 = rf(serviceBindingId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceBindingId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceBindings provides a mock function with given fields:
func (_m *Client) ServiceBindings() (*types.ServiceBindings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceBindings")
	}

	var r0 *types.ServiceBindings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ServiceBindings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ServiceBindings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceBindings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInstance provides a mock function with given fields: serviceInstanceID
func (_m *Client) ServiceInstance(serviceInstanceID string) (*types.ServiceInstance, error) {
	ret := _m.Called(serviceInstanceID)

	if len(ret) == 0 {
		panic("no return value specified for ServiceInstance")
	}

	var r0 *types.ServiceInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.ServiceInstance, error)); ok {
		return rf(serviceInstanceID)
	}
	if rf, ok := ret.Get(0).(func(string) *types.ServiceInstance); ok {
		r0 = rf(serviceInstanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceInstanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInstanceParameters provides a mock function with given fields: serviceInstanceID
func (_m *Client) ServiceInstanceParameters(serviceInstanceID string) (map[string]string, error) {
	ret := _m.Called(serviceInstanceID)

	if len(ret) == 0 {
		panic("no return value specified for ServiceInstanceParameters")
	}

	var r0 map[string]string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (map[string]string, error)); ok {
		return rf(serviceInstanceID)
	}
	if rf, ok := ret.Get(0).(func(string) map[string]string); ok {
		r0 = rf(serviceInstanceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceInstanceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceInstances provides a mock function with given fields:
func (_m *Client) ServiceInstances() (*types.ServiceInstances, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceInstances")
	}

	var r0 *types.ServiceInstances
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ServiceInstances, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ServiceInstances); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceInstances)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceOfferingDetails provides a mock function with given fields: serviceOfferingID
func (_m *Client) ServiceOfferingDetails(serviceOfferingID string) (*types.ServiceOfferingDetails, error) {
	ret := _m.Called(serviceOfferingID)

	if len(ret) == 0 {
		panic("no return value specified for ServiceOfferingDetails")
	}

	var r0 *types.ServiceOfferingDetails
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.ServiceOfferingDetails, error)); ok {
		return rf(serviceOfferingID)
	}
	if rf, ok := ret.Get(0).(func(string) *types.ServiceOfferingDetails); ok {
		r0 = rf(serviceOfferingID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceOfferingDetails)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serviceOfferingID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServiceOfferings provides a mock function with given fields:
func (_m *Client) ServiceOfferings() (*types.ServiceOfferings, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ServiceOfferings")
	}

	var r0 *types.ServiceOfferings
	var r1 error
	if rf, ok := ret.Get(0).(func() (*types.ServiceOfferings, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *types.ServiceOfferings); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceOfferings)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ServicePlan provides a mock function with given fields: servicePlanID
func (_m *Client) ServicePlan(servicePlanID string) (*types.ServicePlan, error) {
	ret := _m.Called(servicePlanID)

	if len(ret) == 0 {
		panic("no return value specified for ServicePlan")
	}

	var r0 *types.ServicePlan
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*types.ServicePlan, error)); ok {
		return rf(servicePlanID)
	}
	if rf, ok := ret.Get(0).(func(string) *types.ServicePlan); ok {
		r0 = rf(servicePlanID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServicePlan)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(servicePlanID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SetForGivenSecret provides a mock function with given fields: ctx, secretName, secretNamespace
func (_m *Client) SetForGivenSecret(ctx context.Context, secretName string, secretNamespace string) error {
	ret := _m.Called(ctx, secretName, secretNamespace)

	if len(ret) == 0 {
		panic("no return value specified for SetForGivenSecret")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, secretName, secretNamespace)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetHTTPClient provides a mock function with given fields: httpClient
func (_m *Client) SetHTTPClient(httpClient *http.Client) {
	_m.Called(httpClient)
}

// SetSMURL provides a mock function with given fields: smURL
func (_m *Client) SetSMURL(smURL string) {
	_m.Called(smURL)
}

// UpdateServiceInstance provides a mock function with given fields: si
func (_m *Client) UpdateServiceInstance(si *types.ServiceInstanceUpdateRequest) (*types.ServiceInstance, error) {
	ret := _m.Called(si)

	if len(ret) == 0 {
		panic("no return value specified for UpdateServiceInstance")
	}

	var r0 *types.ServiceInstance
	var r1 error
	if rf, ok := ret.Get(0).(func(*types.ServiceInstanceUpdateRequest) (*types.ServiceInstance, error)); ok {
		return rf(si)
	}
	if rf, ok := ret.Get(0).(func(*types.ServiceInstanceUpdateRequest) *types.ServiceInstance); ok {
		r0 = rf(si)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*types.ServiceInstance)
		}
	}

	if rf, ok := ret.Get(1).(func(*types.ServiceInstanceUpdateRequest) error); ok {
		r1 = rf(si)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewClient creates a new instance of Client. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *Client {
	mock := &Client{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
