# permissions for end users to edit btpoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: btpoperator-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: btp-manager
    app.kubernetes.io/part-of: btp-manager
    app.kubernetes.io/managed-by: kustomize
  name: btpoperator-editor-role
rules:
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpoperators
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.kyma-project.io
  resources:
  - btpoperators/status
  verbs:
  - get
