apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: sap-btp-manager
  namespace: kyma-system
  labels:
    app.kubernetes.io/managed-by: kcp-kyma-environment-broker
data:
  clientid: dGVzdF9jbGllbnRpZA==
  clientsecret: dGVzdF9jbGllbnRzZWNyZXQ=
  sm_url: dGVzdF9zbV91cmw=
  tokenurl: dGVzdF90b2tlbnVybA==
  cluster_id: dGVzdF9jbHVzdGVyX2lk
