apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: btp-manager-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
