apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: btp-manager-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: btp-manager-manager-role
subjects:
- kind: ServiceAccount
  name: btp-manager-controller-manager
  namespace: btp-manager-system
