apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: btp-manager.kyma-project.io
  name: btp-manager-controller-manager-metrics-service
  namespace: btp-manager-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: btp-manager.kyma-project.io
