---
# Source: sap-btp-operator/templates/pre-delete-job.yml
apiVersion: batch/v1
kind: Job
metadata:
  name: pre-delete-job
  namespace: kyma-system
  labels:
    release: v0.6.8
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  ttlSecondsAfterFinished: 60
  completions: 1
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: sap-btp-operator
      containers:
        - name: pre-delete-operator
          image: "bitnami/kubectl:latest"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              kubectl get servicebindings.services.cloud.sap.com -A --output=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | tail -n +2 | while read -r line; do
                name=$(echo $line | awk '{print $1}')
                namespace=$(echo $line | awk '{print $2}')
                echo "Deleting binding with Name: $name, and Namespace: $namespace"
                timeout 30 kubectl delete servicebindings.services.cloud.sap.com $name -n $namespace
                if [ $? -ne 0 ]; then
                  echo "Failed to delete service binding $name"
                  exit 1
                fi
              done
              echo "Deleting bindings finished successfully"

              kubectl get serviceinstances.services.cloud.sap.com -A --output=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | tail -n +2 | while read -r line; do
                name=$(echo $line | awk '{print $1}')
                namespace=$(echo $line | awk '{print $2}')
                echo "Deleting instance with Name: $name, and Namespace: $namespace"
                timeout 30 kubectl delete serviceinstances.services.cloud.sap.com $name -n $namespace
                if [ $? -ne 0 ]; then
                  echo "Failed to delete service instance $name"
                  exit 1
                fi
              done

              if [ $? -ne 0 ]; then
                exit 1
              fi
              echo "Deleting instances finished successfully"

              kubectl get secrets -l "services.cloud.sap.com/cluster-secret" -A --output=custom-columns=NAME:.metadata.name,NAMESPACE:.metadata.namespace | tail -n +2 | while read -r line; do
                name=$(echo $line | awk '{print $1}')
                namespace=$(echo $line | awk '{print $2}')
                echo "Deleting secret with Name: $name, and Namespace: $namespace"
                timeout 30 kubectl delete secret $name -n $namespace
                if [ $? -ne 0 ]; then
                  echo "Failed to delete secret $name"
                  exit 1
                fi
              done
              echo "Cluster secret deletion finished successfully"

              exit 0
      restartPolicy: Never
