name: Auto bump chart

env:
  ORG: ukff
  BTP_MANAGER_REPO: btp-manager
  GIT_EMAIL: <>
  GIT_NAME: BTP Manager
  USERNAME: ukff

on:
  workflow_dispatch:

jobs:
  auto-bump-chart:
    runs-on: ubuntu-latest
   
    steps:

    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Access
      run: |
        chmod 777 module-overrides/get-latest-chart.sh
        chmod 777 module-overrides/apply-overrides.sh

    - name: Update chart 
      shell: bash
      run: |
        latest=$(sh module-overrides/get-latest-chart.sh)
        echo "TAG=${latest}" >> $GITHUB_ENV

    - name: Make templates
      run: module-overrides/apply-overrides.sh $TAG

    - name: Create PR
      run: |
        git config --global user.email $GIT_EMAIL
        git config --global user.name $GIT_NAME
 
        BRANCH_NAME="bchart-$TAG"
        GIT_MSG="Auto-update charts to $TAG" 

        ls -la ../
        
        git add module-resources
        git add module-chart
        
        git checkout -B $BRANCH_NAME
        
        git status

        commit_result=$(git commit -m "$GIT_MSG")
        if [[ $commit_result == "nothing to commit*" ]]; 
        then
          echo "no new changes, exiting"
          exit 0
        fi
        echo '1'

        git remote set-url origin https://x-access-token:${{ secrets.ACCESS_TOKEN }}@github.com/$ORG/$BTP_MANAGER_REPO.git
        git push --set-upstream origin $BRANCH_NAME -f
        echo '2'

        prs=$(gh pr list -A $USERNAME --state open --json headRefName | jq -r '.[] | .headRefName')
        echo $prs

        if  echo $prs | tr " " '\n' | grep -F -q -x $BRANCH_NAME; then
            echo "open pr already exists, no need to create new one, pr will be updated by push from previous step"
            exit 0
        fi
        echo '3'
        gh pr create -B main --title "$GIT_MSG" --body ""
      env:
        GH_TOKEN: ${{ secrets.ACCESS_TOKEN }}