name: Auto bump chart

env:
  ORG: kyma-project
  BTP_MANAGER_REPO: btp-manager
  GIT_EMAIL: team-gopher+1@sap.com
  GIT_NAME: kyma-btp-manager-bot
on:
  workflow_dispatch:

jobs:
  auto-bump-chart:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v3

    - name: Update chart 
      run: |
        chmod +x hack/update/make-module-chart.sh
        latest=$(sh hack/update/make-module-chart.sh)
        echo "TAG=${latest}" >> $GITHUB_ENV

    - name: Make templates
      run: |
        chmod +x hack/update/make-module-resources.sh
        hack/update/make-module-resources.sh $TAG 

    - name: Stash changes
      run: |
        git status
        git add module-chart 
        git add module-resources
        git stash

    - uses: actions/checkout@v3
      with:
        ref: main
        clean: false

    - name: Create PR
      run: |

        git config --global user.email $GIT_EMAIL
        git config --global user.name $GIT_NAME
 
        BRANCH_NAME="Chart-$TAG"
        GIT_MSG="Auto-update charts to $TAG" 

        git checkout -B $BRANCH_NAME

        git stash apply

        git add module-chart 
        git add module-resources

        if [ -n "$(git status --porcelain)" ]; then
          git commit -m "$GIT_MSG"
        
          git remote set-url origin https://x-access-token:${{ secrets.BOT_TOKEN }}@github.com/$ORG/$BTP_MANAGER_REPO.git
          git push --set-upstream origin $BRANCH_NAME -f
  
          prs=$(gh pr list -A $GIT_NAME --state open --json headRefName | jq -r '.[] | .headRefName')
          if  echo $prs | tr " " '\n' | grep -F -q -x $BRANCH_NAME; then
              echo "open pr already exists, no need to create new one, pr will be updated by push from previous step"
              exit 0
          fi
  
          gh pr create -B main --title "$GIT_MSG" --body ""
        fi
      env:
        GH_TOKEN: ${{ secrets.BOT_TOKEN }}