name: Label validator
on:
  pull_request:
    types: ["opened", "labeled", "unlabeled"]
    branches: [ "main" ]
jobs:
  run-unit-tests:
    uses: ./.github/workflows/label-validator-reusable.yml
    secrets: inherit
