name: Test version submit calling reusable
#  Workflow requires following variables to be defined
#     DOC_URL - location of btp-manager documentation
#     GIT_USER_NAME - user creating head branch and PR
#     GIT_USER_EMAIL - this user email
#     GH_TOOLS_HOST - tools host
#     IMAGE_REPO - name of binary image of the btp-manager executable
#     MODULE_MANIFESTS_REPO_NAME - repository of modules manifests

on:
  workflow_dispatch:
    inputs:
      releaseTag:
        description: "Release Tag"
        default: 'use latest release'
        required: true

jobs:
  submit:
    runs-on: ubuntu-latest

    steps:
      - name: Validate required environment variables
        shell: bash
        run: |
          [ -z "${{ vars.DOC_URL }}" ] && echo "DOC_URL is required" && exit 1 
          [ -z "${{ vars.GIT_USER_EMAIL }}" ] && echo "GIT_USER_EMAIL is required" && exit 1 
          [ -z "${{ vars.GIT_USER_NAME }}" ] && echo "GIT_USER_NAME is required" && exit 1 
          [ -z "${{ vars.GH_TOOLS_HOST }}" ] && echo "GH_TOOLS_HOST is required" && exit 1 
          [ -z "${{ vars.IMAGE_REPO }}" ] && echo "IMAGE_REPO is required" && exit 1 
          [ -z "${{ vars.MODULE_MANIFESTS_REPO_NAME }}" ] && echo "MODULE_MANIFESTS_REPO_NAME is required" && exit 1 
          echo "Validated"

  submit-version-nested:
    name: Nested submit version
    uses: "./.github/workflows/module-version-submit.yaml"
    with:
      releaseTag: ${{ inputs.releaseTag }}
    secrets: inherit
