on:
  pull_request:
    types: [opened]
    branches: [ main ]

name: Change image tag to PR version

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Checkout PR
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr checkout ${{ github.event.pull_request.number }}
      - name: Bump the image
        run: |
          ./hack/bump.sh PR-${{ github.event.number }}
          git config --global user.name "CI"
          git config --global user.email "ci@void"
          git commit -a -m "Bump the image tag"
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git push
