
name: Promote to channel

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - name: Print Vars
        shell: bash
        run: |
          echo "IMAGE_REPO=${{ vars.IMAGE_REPO }}
          echo "LAST_K3S_VERSIONS=${{ vars.LAST_K3S_VERSIONS }}
