#  This GitHub action is designed to run network policies end-to-end (e2e) tests on Kubernetes clusters using the latest k3s distributions.
#  The action is triggered on pull requests to the main branch when network policies related files are changed.

name: Run E2E Network Policies tests on the cluster

on:
  pull_request:
    branches: [main, sm-integration]
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

  workflow_dispatch:
    inputs:
      image-tag:
        description: 'Image tag to test'
        required: true
        default: 'main'
        type: string
      credentials-mode:
        description: 'Credentials mode'
        required: true
        default: 'dummy'
        type: choice
        options:
          - dummy
          - real

jobs:
  run-e2e-network-policies-tests:
    uses: "./.github/workflows/run-e2e-network-policies-tests-reusable.yaml"
    if: ${{ !github.event.pull_request.draft }}
    with:
      image-tag: ${{ github.event_name == 'workflow_dispatch' && inputs.image-tag || format('PR-{0}', github.event.number) }}
      image-repo: europe-docker.pkg.dev/kyma-project/dev/btp-manager
      credentials-mode: ${{ github.event_name == 'workflow_dispatch' && inputs.credentials-mode || 'dummy' }}
    secrets: inherit
