name: Run govulncheck

on:
  pull_request:
    branches: [main, sm-integration]
    paths-ignore:
      - "**.md"
      - "component-config.yaml"
      - "external-images.yaml"
      - "module-chart/**"

permissions:
  contents: read

jobs:
  run-govulncheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Run govulncheck
        uses: golang/govulncheck-action@032d45514ae346b1db93c04b0c90b841c370344f # v1
        with:
          go-version-file: 'go.mod'
          repo-checkout: false
