name: Secret validator
on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Validate secrets
      env:
        TOKEN: ${{ secrets.BOT_TOKEN }}
        PESEL: ${{ secrets.JP_PESEL }}
      run: |
        echo "JP_PESEL length: ${#PESEL}"
        echo "BOT_SECRET length: ${#TOKEN}"